<?xml version="1.0"?>
<robot name="linorobot2_2wd" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find linorobot2_description)/urdf/4wd_properties.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/sensors/depth_sensor.urdf.xacro" />
  <xacro:include filename="$(find linorobot2_description)/urdf/controllers/skid_steer.urdf.xacro" />

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
/>

  <xacro:wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  <xacro:wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:imu/>
  
  <xacro:generic_laser>
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>
  
  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>